@host=http://localhost:5159

POST {{host}}/api/auth/password/change
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiQWRtaW5pc3RyYXRvciIsIlN0YWZmIl0sInN1YiI6ImFkbWluQGFkbWluLmNvbSIsInNpZCI6ImJjMmJlNzM3LWNiZDktNGUzOC04N2M4LWUxZjIxOWMyNjk0NiIsImp0aSI6Ijc3NmE3ODFlLWVjODktNDk2Ny04NzUwLWZmMTAwOThmZmJlYSIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwiZXhwIjoxNzIxNTYzODMyLCJpc3MiOiJKZW1tYSIsImF1ZCI6IkplbW1hIn0.l6aGjaS46hlAsY_i6USclK4cWfoQ3cGKt63i32VuHTs

{
    "currentPassword": "Http404#k",
    "newPassword": "ProjectPie@0218"
}