@host=http://localhost:5159

POST {{host}}/api/basket/item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiQWRtaW5pc3RyYXRvciIsIlN0YWZmIl0sInN1YiI6ImFkbWluQGFkbWluLmNvbSIsInNpZCI6ImViYzQyZTBjLTgxMDQtNGU2NS1iMTkxLWM2NTdkMzQ4ZmY1YyIsImp0aSI6IjBjNDlkMGRhLTg2MWMtNGU3Yy1hOGM2LTc0NThiNmZjMjZiMiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwiZXhwIjoxNzIyMDM1OTAyLCJpc3MiOiJKZW1tYSIsImF1ZCI6IkplbW1hIn0.-QEkTks1KhFlS5zd8IJqPmqJipxv-wY2gkQRQ_MPA1Y

{
        "id": "73eaa3ac-12e3-4f21-96df-0af060e6d572",
        "name": "Shirt",
        "itemType": "Leather",
        "materialType": "Cotton",
        "color": "Green",
        "description": "Has a stain at the collar"
      }